# Site settings
title: My iSearch
header-img: img/home-bg.jpg
email: conorolive@riseup.net
description: "My blog documenting my experience while shadowing a job and while exploring future career options."
baseurl:
url:
twitter_username: conorolive
github_username: conorolive

# Build settings
markdown: kramdown
highlighter: pygments
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
