# Site settings
title: Fuktigt som Helvete
header-img: img/home-bg.jpg
email: conor.e.olive@gmail.com
description: "My personal blog where I generally talk about things too boring for anyone but myself."
baseurl:
url:
twitter_username: conorolive
github_username: conorolive

# Build settings
markdown: kramdown
highlighter: pygments
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
